channels:
  - conda-forge
  - defaults
dependencies:
  - python 
  - pyqt
  - pyqtgraph
  - h5py
  - scipy
  - numpy
  - tqdm
  - pyopencl
  - pocl
  - ipython
  - configparser
  - prody
  - cython
  - mpi4py
  - clblast
  - pip
# has to be done later so that the pip used is the environment one  
#   - pyclblast
