channels:
  - conda-forge
  - defaults
dependencies:
  - python 
  - pyqt
  - pyqtgraph
  - h5py
  - scipy
  - numpy
  - tqdm
  - pyopencl
  - pocl
  - ipython
  - configparser
  - prody
  - cython
  - mpi4py
  - pip
      - pyclblast
